docs: BasicAttnTokenWhitePaper.tex
	pdflatex BasicAttnTokenWhitePaper.tex
	bibtex BasicAttnTokenWhitePaper.aux
	pdflatex BasicAttnTokenWhitePaper.tex



clean:
	rm BasicAttnTokenWhitePaper.log	BasicAttnTokenWhitePaper.toc BasicAttnTokenWhitePaper.aux	  BasicAttnTokenWhitePaper.out	 BasicAttnTokenWhitePaper.blg	  BasicAttnTokenWhitePaper.run.xml  BasicAttnTokenWhitePaper-blx.bib  BasicAttnTokenWhitePaper.bbl
